modLoader="javafml"
loaderVersion="[4,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="llamamod"
version="0.45.06"
displayName="LlamaMod"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Made with Mcreator 2025.3 with the Blockstates plugin"
authors="Omegabird113"
description="A mod with a chaotic set of features based on what I thought would be interesting to play with and/or to code."

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.llamamod]]
    modId="neoforge"
    type="required"
    versionRange="[21.8.31,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.llamamod]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.8]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration